var page = new fcaef.base();
page.templateData = [
 {
     ID: "Page_3",
     Type: fcaef.templates.type.SINGLE_LINE,
     Text: [
         {             ID: "Txt1",             Type: fcaef.templates.type.SINGLE_LINE,             Text: "The breadth and depth of the Advantage change effort highlighted the need for more robust business process management",             CSS: "page3_blueText margin-b10 hideme",         },
         {             ID: "Txt2",             Type: fcaef.templates.type.SINGLE_LINE,             Text: "There was a need for several key enablers to improve chances of successful transformation and reduce the risks of such a large change effort, those key enablers included:",             CSS: "page3_blueText margin-b5 hideme",         },
         {             ID: "Txt3",             Type: fcaef.templates.type.BULLET,       Text: [         {             ID: "Txt4",             Type: fcaef.templates.type.SINGLE_LINE,             Text: "A standard process framework to drive consistency and integration across work streams",             CSS: "page3_green margin-b5 hideme",         },         {             ID: "Txt5",             Type: fcaef.templates.type.SINGLE_LINE,             Text: "A common business process methodology and  notation to unify change efforts and ensure operability of end-to-end process designs",             CSS: "page3_green margin-b5 hideme",         },         {             ID: "Txt6",             Type: fcaef.templates.type.SINGLE_LINE,             Text: "A controlled method of release management for processes across multiple work streams and releases over time",             CSS: "page3_green margin-b5 hideme",         },         {             ID: "Txt7",             Type: fcaef.templates.type.SINGLE_LINE,             Text: "The ability to link and maintain linkages from business process to applications, data and underlying technologies for appropriate impact analysis and risk management",             CSS: "page3_green margin-b5 hideme",         },       ],             CSS: "margin-b10",         },
         {             ID: "Txt8",             Type: fcaef.templates.type.SINGLE_LINE,             Text: "Attempting this was found to be risky without technology support",             CSS: "page3_blueText margin-b10 hideme",         },
         {             ID: "Txt9",             Type: fcaef.templates.type.SINGLE_LINE,             Text: "Business Transformation Office decided to implements a Business Process Management tool to drive more efficient, effective change and to lower risk of execution",             CSS: "page3_blueText margin-b10 hideme",         },
         {             ID: "Txt10",             Type: fcaef.templates.type.SINGLE_LINE,             Text: "The ARIS Design Platform was chosen to meet these needs and to eventually support the business process management goals of the enterprise",             CSS: "page3_blueText margin-b10 hideme",         },
     ],
 }
];
page.audioData = {   File: "page_2",   CueData:[       {         ID: "Txt1",         TriggerOn: "0.1",         CSS: "fadeIn",       },       {         ID: "Txt2",         TriggerOn: "7",         CSS: "fadeIn",       },       {         ID: "Txt4",         TriggerOn: "18",         CSS: "fadeIn",       },       {         ID: "Txt5",         TriggerOn: "24.6",         CSS: "fadeIn",       },       {         ID: "Txt6",         TriggerOn: "34",         CSS: "fadeIn",       },       {         ID: "Txt7",         TriggerOn: "41.47",         CSS: "fadeIn",       },       {         ID: "Txt8",         TriggerOn: "53.30",         CSS: "fadeIn",       },       {         ID: "Txt9",         TriggerOn: "59",         CSS: "fadeIn",       },       {         ID: "Txt10",         TriggerOn: "75",         CSS: "fadeIn",       },      ]}
page.init = function () { fcaef.renderer.render(page.templateData); };
